name: Publish case-log-extract

on:
  push:
    paths:
      - "clinical-archive/case-log-extract/**"
      - ".github/workflows/case-log-extract.yml"

env:
  working_dir: clinical-archive/case-log-extract

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    defaults:
      run:
        working-directory: ${{ env.working_dir }}

    if: github.event.head_commit.message != 'Bump version'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-path: ~/.virtualenvs
          installer-parallel: true
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key:
            "${{ runner.os }}-py-${{ steps.setup-python.outputs.python-version }}-\
            poetry-${{ hashFiles(format('{0}/poetry.lock', env.working_dir)) }}"
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Install project
        run: poetry install --no-interaction
      - name: Build
        id: build
        run: |
          poetry version patch
          poetry build
          echo "::set-output name=version::$(poetry version -s)"
      - uses: EndBug/add-and-commit@v7
        with:
          message: "Bump version"
          add: "clinical-archive/case-log-extract/pyproject.toml"
          tag: check-extract-${{ steps.build.outputs.version }}
      - name: Prepare bundle
        run: |
          mkdir case-extract
          mv dist/*.whl case-extract
          mv src/app.py case-extract
          zip -r ~/case-extract.zip case-extract
      - uses: softprops/action-gh-release@v1
        with:
          name: Check Log Extract ${{ steps.build.outputs.version }}
          tag: check-extract-${{ steps.build.outputs.version }}
          files: |
            ~/case-extract.zip
